include: [
  "config/base.yaml",
  "config/filters.yaml",
]

watermark:
  type: clwe
  secret_dim: [2, 4, 4]
  gamma: 2.0
  beta: 0.001
  dwt_bands: ["LL", "LH", "HL", "HH"]
  seed: 54321

exp_name: cluemark