include: [
  "config/enhanced_inv_dpm_base.yaml",
  "config/filters.yaml",
]

watermark:
  type: clwe
  secret_dim: [4, 1, 1]
  gamma: 4
  beta: 0.01
  dwt_bands: ["LL", "LH", "HL", "HH"]
  seed: 54321

filters:
  - { type: "none" }
  # - { type: "jpeg", quality: 95 }
  - { type: "jpeg", quality: 75 }
  - { type: "jpeg", quality: 25 }
  - { type: "crop", crop: 0.75, scale: 0.75 }
  - { type: "rotate", degrees: 5 }
  - { type: "brightness", factor: 2}
  - { type: "blur", radius: 2}

exp_name: enh_clwe_dwt
