include: [
  "config/base.yaml",
  "config/filters.yaml",
]

watermark:
  type: gaussian_shading
  chacha: true
  seed: 12345
  channel_copy: 1
  hw_copy: 8
  user_number: 1000000
  fpr: 0.000001

output_path: "./images/gaussian_shading_chacha/"
