include: [
  "config/base.yaml",
  "config/filters.yaml",
]

watermark:
  type: tree_ring
  w_seed: 54321
  w_channel: 3
  w_pattern: "ring"
  w_mask_shape: "circle"
  w_radius: 10
  w_measurement: "l1_complex"
  w_injection: "complex"
  w_pattern_const: 0.0

exp_name: tree_ring
